homeassistant:
  name: Team Shark Bait
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 14
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  
group: !include groups.yaml                       
switch: !include switch.yaml 
scene: !include scene.yaml  
light: !include light.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml
automation: !include_dir_list automations/
alarm_control_panel: !include alarm.yaml
input_boolean: !include input_boolean.yaml
ios: !include ios.yaml
script: !include script.yaml
device_tracker:

emulated_hue:
  host_ip: !secret hass_ip
  exposed_domains:
    - light
    - switch
    - group

updater:
#discovery:
config:
frontend:
conversation:
history:
logbook:
sun:
mqtt:
  broker: !secret hass_ip
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

zha:
  usb_path: /dev/ttyUSB1
  database_path: /home/homeassistant/.homeassistant/zha.db


#panel_custom:
#    - name: alarm
#      sidebar_title: Alarm
#      sidebar_icon: mdi:security-home
#      config:
#          alarmid: alarm_control_panel.ha_alarm    

# Purge Database After 7 Days
recorder:
  purge_days: 7

# Front End Configuration Options & SSL Certificate for Remote Access
http:
  api_password: !secret http_password
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

# Text to speech
tts:
  platform: google
    
zone:
  name: Presence Office
  latitude: !secret presence_latitude
  longitude: !secret presence_longitude

media_player:
  - platform: apple_tv
    name: Bedroom Apple TV
    host: !secret bedroom_atv
    login_id: !secret atv_loginid    