alias: 'Trigger alarm while armed away'
trigger:
 - platform: state
   entity_id: binary_sensor.front_door
   state: 'on'
 - platform: state
   entity_id: binary_sensor.visonic_mct340_e_0b3b980d_1
   state: 'on'
condition:
 - condition: state
   entity_id: alarm_control_panel.ha_alarm
   state: 'armed_away'
action:
 - service: alarm_control_panel.alarm_trigger
   entity_id: alarm_control_panel.ha_alarm
 - service: notify.ios_mikesiphone
   data:
     title: "ALARM TRIGGERED"
     message: "The alarm has been triggered"
 - service: light.turn_on
   entity_id: group.dining_room_track_lights
   data:
     brightness: 255
     color_name: red
     transition: 0
 - service: switch.turn_on
   entity_id: group.living_room
 - service: homeassistant.turn_on
   entity_id: group.kitchen